Repository Vibe-Fiction/AI-dea, pull requests merged in 2025-08, with the labels that each got.

#2 fix: Entity 연관관계 오류 해결
  src/main/java/com/spring/aidea/vibefiction/entity/AiInteractionLogs.java
  src/main/java/com/spring/aidea/vibefiction/entity/Chapters.java
  src/main/java/com/spring/aidea/vibefiction/entity/Genres.java
  src/main/java/com/spring/aidea/vibefiction/entity/NovelGenres.java
  src/main/java/com/spring/aidea/vibefiction/entity/Novels.java
  src/main/java/com/spring/aidea/vibefiction/entity/Proposals.java
  src/main/java/com/spring/aidea/vibefiction/entity/Users.java
  src/main/java/com/spring/aidea/vibefiction/repository/NovelsRepository.java
  src/test/java/com/spring/aidea/bsh/MainPageTest.java
Labels: bug

#9 Refactoring/ 변경된 디렉토리 구조를 반영한 리팩토링
  src/main/java/com/spring/aidea/vibefiction/controller/MainPageControllerSH.java
  src/main/java/com/spring/aidea/vibefiction/dto/response/NovelsResponseDtoSH.java
  src/main/java/com/spring/aidea/vibefiction/entity/Novels.java
  src/main/java/com/spring/aidea/vibefiction/global/config/SecurityConfig.java
  src/main/java/com/spring/aidea/vibefiction/global/exception/ErrorCode.java
  src/main/java/com/spring/aidea/vibefiction/repository/NovelsRepository.java
  src/main/java/com/spring/aidea/vibefiction/service/MainPageServiceSH.java
Labels: refactoring

#11 [Docs] 프로젝트 협업 규칙 및 가이드 문서 초기 설정 (#10)
  .editorconfig
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  docs/advanced-git-guide.md
  docs/code-style.md
  docs/project-structure.md
  docs/workflow.md
Labels: discussion, docs, feature

#15 [Docs]: 프로젝트 협업 규칙 및 템플릿 시스템 구축 (#14)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: docs, refactor

#13 docs: 20250804 ~ 202508011 회의록 문서 추가 (#12)
  docs/meetings/2025-08-04-meeting.md
  docs/meetings/2025-08-05-meeting.md
  docs/meetings/2025-08-06-meeting.md
  docs/meetings/2025-08-07-meeting.md
  docs/meetings/2025-08-08-meeting.md
  docs/meetings/2025-08-11-meeting.md
Labels: discussion, docs, feature

#30 [Feat]: JWT 인증 및 실시간 중복 체크 기능 구현 (#29)
  src/main/java/com/spring/aidea/vibefiction/controller/AuthControllerKO.java
  src/main/java/com/spring/aidea/vibefiction/dto/response/user/UserResponseKO.java
  src/main/java/com/spring/aidea/vibefiction/global/config/SecurityConfig.java
  src/main/java/com/spring/aidea/vibefiction/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/spring/aidea/vibefiction/global/jwt/JwtProvider.java
  src/main/java/com/spring/aidea/vibefiction/service/LoginServiceKO.java
Labels: area: backend, feature, performance

#28 [Docs]: Git 워크플로우 및 코드 스타일 가이드 업데이트 (#27)
  docs/code-style.md
  docs/workflow.md
Labels: docs

#34 [Feat]: 핵심 기능(소설/제안 생성) 구현 및 공식 인증 시스템 통합 (#18, #25, #33)
  src/main/java/com/spring/aidea/vibefiction/controller/AiControllerTj.java
  src/main/java/com/spring/aidea/vibefiction/controller/AuthControllerTj.java
  src/main/java/com/spring/aidea/vibefiction/controller/ChapterControllerTj.java
  src/main/java/com/spring/aidea/vibefiction/controller/NovelControllerTj.java
  src/main/java/com/spring/aidea/vibefiction/controller/ProposalControllerTj.java
  src/main/java/com/spring/aidea/vibefiction/dto/request/aiInteractionLog/AiContinueRequestTj.java
  src/main/java/com/spring/aidea/vibefiction/dto/request/aiInteractionLog/AiRecommendNovelRequestTj.java
  src/main/java/com/spring/aidea/vibefiction/dto/request/auth/LoginRequestTj.java
  src/main/java/com/spring/aidea/vibefiction/dto/request/chapter/ChapterCreateRequestTj.java
  src/main/java/com/spring/aidea/vibefiction/dto/request/novel/NovelCreateRequestTj.java
  src/main/java/com/spring/aidea/vibefiction/dto/request/proposal/ProposalCreateRequestTj.java
  src/main/java/com/spring/aidea/vibefiction/dto/response/aiInteractionLog/AiContinueResponseTj.java
  src/main/java/com/spring/aidea/vibefiction/dto/response/aiInteractionLog/AiRecommendNovelResponseTj.java
  src/main/java/com/spring/aidea/vibefiction/dto/response/auth/LoginResponseTj.java
  src/main/java/com/spring/aidea/vibefiction/dto/response/chapter/ChapterCreateResponseTj.java
  src/main/java/com/spring/aidea/vibefiction/dto/response/novel/NovelCreateResponseTj.java
  src/main/java/com/spring/aidea/vibefiction/dto/response/proposal/ProposalCreateResponseTj.java
  src/main/java/com/spring/aidea/vibefiction/dto/response/proposal/ProposalSummaryResponseTj.java
  src/main/java/com/spring/aidea/vibefiction/entity/AiInteractionLogs.java
  src/main/java/com/spring/aidea/vibefiction/entity/Chapters.java
  src/main/java/com/spring/aidea/vibefiction/entity/NovelGenres.java
  src/main/java/com/spring/aidea/vibefiction/entity/Novels.java
  src/main/java/com/spring/aidea/vibefiction/entity/Proposals.java
  src/main/java/com/spring/aidea/vibefiction/global/common/ApiResponse.java
  src/main/java/com/spring/aidea/vibefiction/global/config/SecurityConfig.java
  src/main/java/com/spring/aidea/vibefiction/global/exception/BusinessException.java
  src/main/java/com/spring/aidea/vibefiction/global/jwt/JwtHelperTj.java
  src/main/java/com/spring/aidea/vibefiction/global/jwt/JwtProvider.java
  src/main/java/com/spring/aidea/vibefiction/repository/ChaptersRepository.java
  src/main/java/com/spring/aidea/vibefiction/repository/ProposalsRepository.java
  src/main/java/com/spring/aidea/vibefiction/service/AiAssistServiceTj.java
  src/main/java/com/spring/aidea/vibefiction/service/AuthServiceTj.java
  src/main/java/com/spring/aidea/vibefiction/service/ChapterServiceTj.java
  src/main/java/com/spring/aidea/vibefiction/service/MockAIServiceTj.java
  src/main/java/com/spring/aidea/vibefiction/service/NovelServiceTj.java
  src/main/java/com/spring/aidea/vibefiction/service/ProposalServiceTj.java
Labels: area: backend, feature, refactor, enhancement

#40 Refactor: 장르 관리 방식을 Enum으로 개선하여 타입 안정성 확보 (#39)
  src/main/java/com/spring/aidea/vibefiction/dto/request/novel/NovelCreateRequestTj.java
  src/main/java/com/spring/aidea/vibefiction/dto/response/novel/NovelsResponseDtoSH.java
  src/main/java/com/spring/aidea/vibefiction/entity/Genres.java
  src/main/java/com/spring/aidea/vibefiction/repository/GenresRepository.java
  src/main/java/com/spring/aidea/vibefiction/service/NovelServiceTj.java
Labels: area: backend, feature, refactor, enhancement

#58 [Feature] 마이페이지 토큰검증연동 및 새 소설쓰기 버튼생성 (#57)
  src/main/java/com/spring/aidea/vibefiction/controller/MyPageControllerSH.java
  src/main/resources/ application-template.yml
  src/main/resources/static/css/index.css
  src/main/resources/static/css/style.css
  src/main/resources/static/img/DefaultNovelLogo.png
  src/main/resources/static/js/app.js
  src/main/resources/static/js/config/routes-config.js
  src/main/resources/static/js/pages/my-page.js
  src/main/resources/static/js/utils/auth.js
  src/main/resources/static/js/utils/token.js
  src/main/resources/static/js/utils/ui.js
  src/main/resources/templates/fragments/mainHeader.html
  src/main/resources/templates/index.html
Labels: area: backend, design, area: frontend, enhancement, security

#59 Revert "[Feature] 마이페이지 토큰검증연동 및 새 소설쓰기 버튼생성 (#57)"
  src/main/java/com/spring/aidea/vibefiction/controller/MyPageControllerSH.java
  src/main/resources/ application-template.yml
  src/main/resources/static/css/index.css
  src/main/resources/static/css/style.css
  src/main/resources/static/img/DefaultNovelLogo.png
  src/main/resources/static/js/app.js
  src/main/resources/static/js/config/routes-config.js
  src/main/resources/static/js/pages/my-page.js
  src/main/resources/static/js/utils/auth.js
  src/main/resources/static/js/utils/token.js
  src/main/resources/static/js/utils/ui.js
  src/main/resources/templates/fragments/mainHeader.html
  src/main/resources/templates/index.html
Labels: bug

#70 [ feature , bugfix ]: 페이지별 라우트가드 및 검증페이지 이동 시 로그인 이벤트, 무한스크롤 버그픽스 (#61)
  src/main/java/com/spring/aidea/vibefiction/controller/MyPageControllerSH.java
  src/main/resources/static/css/index.css
  src/main/resources/static/css/style.css
  src/main/resources/static/js/app.js
  src/main/resources/static/js/config/routes-config.js
  src/main/resources/static/js/pages/chapters-page.js
  src/main/resources/static/js/pages/home.js
  src/main/resources/static/js/pages/vote-page.js
  src/main/resources/static/js/utils/auth.js
  src/main/resources/static/js/utils/ui.js
  src/main/resources/templates/index.html
  src/main/resources/templates/my-page.html
  src/main/resources/templates/vote-page.html
Labels: area: backend, bug, design, feature, area: frontend, enhancement

#84 [Docs]: 최종 문서 업데이트 (#82)
  README.md
  docs/architecture/ai-usage-and-prompting.md
  docs/planning/vibe-fiction-project-overview-and-features.md
  docs/rules/STORY_SUMMARY_POLICY.md
Labels: docs

#86 [feature] 투표 마감시 소설 페이지로 이동
  src/main/java/com/spring/aidea/vibefiction/controller/VoteControllerMj.java
  src/main/java/com/spring/aidea/vibefiction/dto/request/vote/VoteFinalizeRequestMj.java
  src/main/java/com/spring/aidea/vibefiction/dto/response/vote/VoteListAndClosingResponseMj.java
  src/main/java/com/spring/aidea/vibefiction/entity/Proposals.java
  src/main/java/com/spring/aidea/vibefiction/global/config/SecurityConfig.java
  src/main/java/com/spring/aidea/vibefiction/repository/ProposalsRepository.java
  src/main/java/com/spring/aidea/vibefiction/service/VoteScheduler.java
  src/main/java/com/spring/aidea/vibefiction/service/VoteServiceMj.java
  src/main/resources/static/js/pages/vote-page.js
  src/test/java/com/spring/aidea/vibefiction/service/VoteSchedulerTest.java
Labels: area: backend, bug, enhancement
